version: '2.3'
services:
  dhcpd:
    image: networkboot/dhcpd
    volumes:
      - ./dhcpd:/data:rw
    network_mode: host
#    networks:
#      mgmt:
#        ipv4_address: 10.0.4.254
  tftp:
    image: pghalliday/tftp
    volumes:
      - /infra/host/storage/tftpboot:/var/tftpboot:ro
#    network_mode: host
#    ports:
#      - "69:69/udp"
    networks:
      dmz:
        ipv4_address: 10.0.2.253
  server:
    build: freeipa-container
    hostname: ipa.whiskey.works
    environment:
      - IPA_SERVER_HOSTNAME=ipa.whiskey.works
    networks:
      dmz:
        ipv4_address: 10.0.2.2
        aliases:
          - ipa.whiskey.works
          - ns1.murderhaus.com
    volumes:
      - /infra/host/storage/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
networks:
  mgmt:
    driver: macvlan
    driver_opts:
      parent: bond0.4
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24
          gateway: 10.0.4.1
  dmz:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: bond0.2
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1
        - subnet: fd50:8086:becd:e09f::/64
