version: '2.3'
services:
  server:
    build: freeipa-container
    hostname: ipa.whiskey.works
    environment:
      - IPA_SERVER_HOSTNAME=ipa.whiskey.works
    networks:
      default:
        aliases:
          - ipa.whiskey.works
          - ns1.murderhaus.com
    volumes:
      - /infra/host/storage/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
networks:
  default:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: bond0.1502
    ipam:
      driver: default
      config:
        - subnet: 10.5.2.0/24
          gateway: 10.5.2.1
        - subnet: fd50:8086:becd:e09f::/64
